### ISSUE TITLE
Mimimal script to run the experiment 

### ISSUE THREAD

**Issue by enkeejunior1** [ltgoslo/bert-in-context#1]
Hi,

Thank you for your really exciting work. I believe this work will boost the research community's efforts on MLMs.

By the way, could you provide a minimal script to run the experiment from the paper? It would greatly reduce the amount of work needed to reproduce the results.

Thank you in advance.

**Comment by davda54** [comment]
Hi, thanks! The scripts for all experiments in the paper should already be uploaded here, what exactly are you missing?

**Comment by enkeejunior1** [comment]
Ah, all the code runs in ```python3 <code>``` ..! I thought the code needed to be run as `<script>.sh` to be reproducible. My apologies. 

I will close the issue. Thanks for the prompt response.
